/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/bear.glb --output components/Bear.js 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bear.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} />
      <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} />
      <mesh geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} />
      <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} />
      <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} />
      <mesh geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} />
      <mesh geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} />
      <mesh geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} />
      <mesh geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} />
      <mesh geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} />
      <mesh geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} />
      <mesh geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} />
      <mesh geometry={nodes.Cube012.geometry} material={nodes.Cube012.material} />
    </group>
  )
}

useGLTF.preload('/bear.glb')
