/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/headset.glb --output components/Headset.js 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Headset(props) {
  const { nodes, materials } = useGLTF('/headset.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/headset.glb')

