/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/left_controller_v1.glb --output components/LeftController.js 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/left_controller_v1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
      <mesh geometry={nodes.Torus.geometry} material={nodes.Torus.material} />
    </group>
  )
}

useGLTF.preload('/left_controller_v1.glb')
