/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/vr_headset_v2.glb --output components/VRHeadset.js 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/vr_headset_v2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} />
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} />
      <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} />
      <mesh geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} />
    </group>
  )
}

useGLTF.preload('/vr_headset_v2.glb')
